config/routes.rb
Easytorrent::Application.routes.draw do

  resources :contacts do    
    collection do
      get 'thanks'
    end
  end

  devise_for :users

  resources :searches do
    collection do
      get 'all'
      get 'show_ajax/:id' => 'searches#show_ajax'
    end
  end

   root :to => 'searches#new'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json

  before_filter :authenticate_user!, :except => [:new, :create, :thanks]

  def thanks
    
  end

  def index
    @contacts = Contact.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to thanks_contacts_path, notice: 'El mensaje fue enviado.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact, :html =>{:class =>"form-horizontal"}) do |f| %>

  <div class="control-group">
    <label class="control-label" for="inputName">Nombre</label>
    <div class="controls">
       <%= f.text_field :name %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputMail">Email</label>
    <div class="controls">
      <%= f.text_field :mail %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputMail">Mensaje</label>
    <div class="controls">
      <%= f.text_area :message, :cols => 10, :rows => 10 %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit "Enviar mensaje",  :class => "btn"%>
    </div>
  </div> 

<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Mail</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.name %></td>
    <td><%= contact.mail %></td>
    <td><%= contact.message %></td>
    <td><%= link_to 'Show', contact %></td>
    <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
    <td><%= link_to 'Destroy', contact, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/contacts/new.html.erb
<div class='hero-unit'>
      <div class="row">
        <div class="span5">
          <h2>Contacto</h2>
          <%= render 'form' %>
        </div>
      </div>
</div>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @contact.name %>
</p>

<p>
  <b>Mail:</b>
  <%= @contact.mail %>
</p>

<p>
  <b>Message:</b>
  <%= @contact.message %>
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/thanks.html.erb
<div class="well">
<p>
  Espero que la experiencia del sitio sea de su agrado.
</p>
<p>
  Gracias por contactarse.
</p>
</div>