config/routes.rb
Easytorrent::Application.routes.draw do

  resources :contacts do    
    collection do
      get 'thanks'
    end
  end

  devise_for :users

  resources :searches do
    collection do
      get 'all'
      get 'show_ajax/:id' => 'searches#show_ajax'
    end
  end

   root :to => 'searches#new'

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "EasyTorrents", root_path, :class => 'brand' %>
<ul class="nav">

   <li>
    <%= link_to('Contacto', new_contact_path) %>
   </li>
   <li>
    <%= link_to('About Joao', searches_path) %>        
   </li>


  <% if user_signed_in? %>
    <li>
    <%= link_to('Mensajes', contacts_path) %>        
    </li>
    <li>
    <%= link_to('Búsquedas', all_searches_path) %>        
    </li>
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>  
    </li>
  <% end %>

</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EasyTorrent</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>